### PR TITLE
adblock: improved css rules (again)

### PR DESCRIPTION
**Pull request by AvinashReddy3108**
merged css rules from popular sources, credits included

### CODE REVIEW

**Comment by AvinashReddy3108** [comment]
Hopefully, with this patch we can now have just one extension to kill all annoyances :)

**Comment by AvinashReddy3108** [comment]
Do note that this also removes the Download button, which might be a problem for Premium users.

**Comment by CharlieS1103** [comment]
Didnt I just merge this?

**Comment by AvinashReddy3108** [comment]
> Didnt I just merge this?

The commit/PR title is the same, but the CSS rules have changed a lot in comparison..
Also added the credits to the sources of these CSS rules..

**Pull request merged**
